export const postData = [
  // Travel category
  {
    id: 1,
    title: "Exploring the World",
    content: "This is a fascinating post about exploring the world. It covers various aspects of travel, culture, and adventures in different places.",
    image: "/images/post-image1.jpg",
    background: "bg-blue-300",
    author: "Hemanth Sayimpu",
    date: "2024-11-01",
    categories: ["Travel"],
    tags: ["Culture", "Exploration", "Wanderlust"],
    readingTime: "5 min read",
    slug: "exploring-the-world",
    metaDescription: "A journey through the wonders of travel, culture, and adventure across the globe.",
    isFeatured: true,
    commentsCount: 12,
    shares: 56,
  },
  {
    id: 2,
    title: "Travel Tips and Tricks",
    content: "A post about travel tips, including packing strategies, local tips, and ways to make the most out of your trip.",
    image: "/images/post-image2.jpg",
    background: "bg-green-300",
    author: "Hemanth Sayimpu",
    date: "2024-10-28",
    categories: ["Travel"],
    tags: ["Packing", "Travel Hacks"],
    readingTime: "4 min read",
    slug: "travel-tips-and-tricks",
    metaDescription: "Essential travel tips for making your trips more enjoyable and efficient.",
    isFeatured: false,
    commentsCount: 7,
    shares: 40,
  },
  {
    id: 3,
    title: "Hidden Gems in Europe",
    content: "A journey through some of Europe's lesser-known but highly captivating travel spots.",
    image: "/images/post-image3.jpg",
    background: "bg-red-300",
    author: "Hemanth Sayimpu",
    date: "2024-10-15",
    categories: ["Travel"],
    tags: ["Europe", "Hidden Gems"],
    readingTime: "6 min read",
    slug: "hidden-gems-in-europe",
    metaDescription: "Explore Europe's best-kept secrets through stunning, off-the-radar destinations.",
    isFeatured: true,
    commentsCount: 15,
    shares: 73,
  },
  {
    id: 4,
    title: "Cultural Insights",
    content: "Exploring the deep cultural history and fascinating traditions around the world.",
    image: "/images/post-image4.jpg",
    background: "bg-yellow-300",
    author: "Hemanth Sayimpu",
    date: "2024-10-10",
    categories: ["Travel"],
    tags: ["Traditions", "Cultural History"],
    readingTime: "7 min read",
    slug: "cultural-insights",
    metaDescription: "Dive into the diverse cultural traditions that make each destination unique.",
    isFeatured: false,
    commentsCount: 5,
    shares: 32,
  },
  {
    id: 5,
    title: "Mountain Adventures",
    content: "A post about exhilarating mountain adventures, covering hikes, views, and essential gear.",
    image: "/images/post-image5.jpg",
    background: "bg-purple-300",
    author: "Hemanth Sayimpu",
    date: "2024-09-30",
    categories: ["Travel"],
    tags: ["Hiking", "Mountains", "Nature"],
    readingTime: "6 min read",
    slug: "mountain-adventures",
    metaDescription: "Gear up for the best mountain adventures with tips on hikes and essential gear.",
    isFeatured: true,
    commentsCount: 9,
    shares: 48,
  },
  {
    id: 6,
    title: "Urban Escapes",
    content: "Discover the hidden retreats within bustling cities, from quiet cafes to serene parks.",
    image: "/images/post-image6.jpg",
    background: "bg-teal-300",
    author: "Hemanth Sayimpu",
    date: "2024-09-25",
    categories: ["Travel"],
    tags: ["Urban Retreat", "Peaceful Places"],
    readingTime: "5 min read",
    slug: "urban-escapes",
    metaDescription: "Find tranquility amidst the hustle and bustle of city life with these urban escapes.",
    isFeatured: false,
    commentsCount: 8,
    shares: 39,
  },
  // Photography category
  {
    id: 7,
    title: "Capturing Nature's Beauty",
    content: "A post that explores the best tips and techniques for photographing nature and landscapes.",
    image: "/images/post-image7.jpg",
    background: "bg-orange-300",
    author: "Hemanth Sayimpu",
    date: "2024-09-20",
    categories: ["Photography"],
    tags: ["Nature", "Photography Tips", "Landscapes"],
    readingTime: "6 min read",
    slug: "capturing-natures-beauty",
    metaDescription: "Learn how to capture stunning landscapes and nature shots with expert photography tips.",
    isFeatured: true,
    commentsCount: 12,
    shares: 55,
  },
  {
    id: 8,
    title: "Urban Photography",
    content: "Discover the world of urban photography and how to capture cityscapes and architecture.",
    image: "/images/post-image8.jpg",
    background: "bg-pink-300",
    author: "Hemanth Sayimpu",
    date: "2024-09-15",
    categories: ["Photography"],
    tags: ["Urban", "Cityscapes", "Photography Techniques"],
    readingTime: "7 min read",
    slug: "urban-photography",
    metaDescription: "A guide to mastering urban photography, capturing the essence of city life.",
    isFeatured: false,
    commentsCount: 9,
    shares: 48,
  },
  {
    id: 9,
    title: "Night Photography Essentials",
    content: "Master the art of capturing beautiful images at night with tips on lighting and exposure.",
    image: "/images/post-image9.jpg",
    background: "bg-indigo-300",
    author: "Hemanth Sayimpu",
    date: "2024-09-10",
    categories: ["Photography"],
    tags: ["Night Photography", "Lighting", "Exposure"],
    readingTime: "6 min read",
    slug: "night-photography-essentials",
    metaDescription: "Essential tips for capturing stunning photos in low light and at night.",
    isFeatured: true,
    commentsCount: 8,
    shares: 53,
  },
  {
    id: 10,
    title: "Portrait Photography Tips",
    content: "How to take professional-looking portraits with basic equipment and lighting.",
    image: "/images/post-image10.jpg",
    background: "bg-teal-300",
    author: "Hemanth Sayimpu",
    date: "2024-09-05",
    categories: ["Photography"],
    tags: ["Portrait", "Photography Tips", "Lighting Techniques"],
    readingTime: "5 min read",
    slug: "portrait-photography-tips",
    metaDescription: "A guide to taking stunning portraits with minimal gear and the right lighting.",
    isFeatured: false,
    commentsCount: 6,
    shares: 32,
  },
  {
    id: 11,
    title: "Travel Photography Hacks",
    content: "Learn how to make the most of your travel photography experience with these essential hacks.",
    image: "/images/post-image11.jpg",
    background: "bg-yellow-300",
    author: "Hemanth Sayimpu",
    date: "2024-08-28",
    categories: ["Photography"],
    tags: ["Travel Photography", "Photography Hacks"],
    readingTime: "5 min read",
    slug: "travel-photography-hacks",
    metaDescription: "Capture your travels in the most stunning way with these pro photography tips.",
    isFeatured: true,
    commentsCount: 7,
    shares: 50,
  },
  // Music category
  {
    id: 12,
    title: "Discovering New Music Genres",
    content: "Explore the world of music and discover new genres and styles you may not have heard before.",
    image: "/images/post-image12.jpg",
    background: "bg-blue-200",
    author: "Hemanth Sayimpu",
    date: "2024-08-22",
    categories: ["Music"],
    tags: ["Music", "Genres", "Discover"],
    readingTime: "5 min read",
    slug: "discovering-new-music-genres",
    metaDescription: "A guide to expanding your musical horizons by exploring new genres.",
    isFeatured: true,
    commentsCount: 5,
    shares: 34,
  },
  {
    id: 13,
    title: "The Evolution of Rock Music",
    content: "An in-depth look at the history and evolution of rock music, from its roots to modern interpretations.",
    image: "/images/post-image13.jpg",
    background: "bg-green-300",
    author: "Hemanth Sayimpu",
    date: "2024-08-18",
    categories: ["Music"],
    tags: ["Rock", "Music History", "Evolution"],
    readingTime: "6 min read",
    slug: "the-evolution-of-rock-music",
    metaDescription: "Discover how rock music evolved over the decades and its impact on the world.",
    isFeatured: false,
    commentsCount: 10,
    shares: 41,
  },
  {
    id: 14,
    title: "The Magic of Classical Music",
    content: "Delve into the rich history and timeless beauty of classical music from around the world.",
    image: "/images/post-image14.jpg",
    background: "bg-purple-300",
    author: "Hemanth Sayimpu",
    date: "2024-08-12",
    categories: ["Music"],
    tags: ["Classical Music", "Timeless Beauty"],
    readingTime: "5 min read",
    slug: "the-magic-of-classical-music",
    metaDescription: "Explore the world of classical music, from its origins to its modern-day influence.",
    isFeatured: true,
    commentsCount: 6,
    shares: 33,
  },
  {
    id: 15,
    title: "Musical Instruments Explained",
    content: "A breakdown of different musical instruments and how they produce their unique sounds.",
    image: "/images/post-image15.jpg",
    background: "bg-red-300",
    author: "Hemanth Sayimpu",
    date: "2024-08-05",
    categories: ["Music"],
    tags: ["Instruments", "Music Theory"],
    readingTime: "6 min read",
    slug: "musical-instruments-explained",
    metaDescription: "Get to know the ins and outs of different musical instruments and how they create sound.",
    isFeatured: false,
    commentsCount: 8,
    shares: 42,
  },
  // Series category
  {
    id: 16,
    title: "Top 10 TV Series to Watch",
    content: "A list of the top 10 TV series everyone should watch, ranging from dramas to comedies.",
    image: "/images/post-image16.jpg",
    background: "bg-teal-300",
    author: "Hemanth Sayimpu",
    date: "2024-07-30",
    categories: ["Series"],
    tags: ["TV Series", "Entertainment"],
    readingTime: "6 min read",
    slug: "top-10-tv-series-to-watch",
    metaDescription: "A curated list of top TV series that are a must-watch for entertainment lovers.",
    isFeatured: true,
    commentsCount: 9,
    shares: 54,
  }
];
